#!/usr/bin/env bash

set -e

OUTPUT_PRODUCT_NAME="Beyond.NET.Sample.Managed"

VERBOSITY_LEVEL="normal"

echo "Building ${OUTPUT_PRODUCT_NAME} managed"
dotnet publish -v "${VERBOSITY_LEVEL}" /p:Configuration=Release
