#!/usr/bin/env bash

set -e

DOTNET_PATH=`which dotnet`
DOTNET_VERSION=`${DOTNET_PATH} --version`
DOTNET_VERSION_MAJOR_AND_MINOR=${DOTNET_VERSION:0:3}

cd "../../NativeAOT.CodeGeneratorInputSample"
./publish_managed

cd "../../NativeAOT.CodeGenerator.CLI"
./publish_macos_universal

cd "../Samples"
echo "Generating .NET Native Bindings"
../NativeAOT.CodeGenerator.CLI/bin/Release/net${DOTNET_VERSION_MAJOR_AND_MINOR}/osx-universal/publish/NativeAOT.CodeGenerator.CLI "NativeAOTCodeGeneratorSampleConfig.json"

cd "NativeAOT.CodeGeneratorOutputSample"
./publish_macos_universal