#!/usr/bin/env bash

set -e

DOTNET_PATH=`which dotnet`
DOTNET_VERSION=`${DOTNET_PATH} --version`
DOTNET_VERSION_MAJOR_AND_MINOR=${DOTNET_VERSION:0:3}

cd "../../Beyond.NET.Sample.Managed"
./publish_managed

cd "../../NativeAOT.CodeGenerator.CLI"
./publish_linux_x64

cd "../Samples"
echo "Generating .NET Native Bindings"
../NativeAOT.CodeGenerator.CLI/bin/Release/net${DOTNET_VERSION_MAJOR_AND_MINOR}/linux-x64/publish/NativeAOT.CodeGenerator.CLI "Beyond.NET.Sample_Config.json"

cd "Beyond.NET.Sample.Native"
./publish_linux_x64