#!/usr/bin/env bash

set -e

OUTPUT_PRODUCT_NAME="newguid"
LIBRARY_NAME="BeyondDotNETSampleNative"
LIBRARY_FILE_NAME="lib${LIBRARY_NAME}.so"
C_FILE_NAME="newguid.c"

BUILD_DIR="bin"

DOTNET_PATH=`which dotnet`
DOTNET_VERSION=`${DOTNET_PATH} --version`
DOTNET_VERSION_MAJOR_AND_MINOR=${DOTNET_VERSION:0:3}
DOTNET_TARGET_FRAMEWORK="net${DOTNET_VERSION_MAJOR_AND_MINOR}"

echo "Making directory for ${OUTPUT_PRODUCT_NAME} build"
mkdir -p "${BUILD_DIR}"

OUTPUT_FILE_PATH_X64="${OUTPUT_PRODUCT_NAME}"

C_HEADER_FILE_NAME="Generated_C.h"

./build_dependencies_linux_x64

cd "${BUILD_DIR}"

echo "Copying native library"
cp "../../bin/Release/${DOTNET_TARGET_FRAMEWORK}/linux-x64/publish/${LIBRARY_FILE_NAME}" "${LIBRARY_FILE_NAME}"

echo "Copying C header file"
cp "../../../Generated/${C_HEADER_FILE_NAME}" "${C_HEADER_FILE_NAME}"

echo "Copying C file"
cp "../${C_FILE_NAME}" "${C_FILE_NAME}"

echo "Building ${OUTPUT_PRODUCT_NAME} for x64"
clang -Wl,-rpath,. -L. -l${LIBRARY_NAME} -arch "x86_64" -o "${OUTPUT_FILE_PATH_X64}" "${C_FILE_NAME}"

echo "Deleting ${C_HEADER_FILE_NAME}"
rm "${C_HEADER_FILE_NAME}"

echo "Deleting ${C_FILE_NAME}"
rm "${C_FILE_NAME}"