#!/usr/bin/env bash

set -e

ORIG_PWD=$PWD

source "../prepare_xcode_scripting_environment"

DOTNET_PATH=`which dotnet`
DOTNET_VERSION=`${DOTNET_PATH} --version`
DOTNET_VERSION_MAJOR_AND_MINOR=${DOTNET_VERSION:0:3}

# Build Beyond.NET.CodeGenerator.CLI
cd "../../Generator/Beyond.NET.CodeGenerator.CLI"
./publish_macos_universal

cd "${ORIG_PWD}"

# Build .NET Sample Managed
cd "../Beyond.NET.Sample.Managed"
./publish_managed

cd "${ORIG_PWD}"

# Generate Native Bindings and build an Apple Universal XCFramework
cd ".."

GENERATOR_PATH="../Generator/Beyond.NET.CodeGenerator.CLI/bin/Release/net${DOTNET_VERSION_MAJOR_AND_MINOR}/osx-universal/publish/beyondnetgen"
CONFIG_PATH="Beyond.NET.Sample_BuildConfig.json"

"${GENERATOR_PATH}" "${CONFIG_PATH}"