#!/usr/bin/env bash

set -e

OUTPUT_PRODUCT_NAME="transform"
LIBRARY_NAME="BeyondDotNETSampleNative"
LIBRARY_FILE_NAME="lib${LIBRARY_NAME}.dylib"
C_FILE_NAME="transform.c"

BUILD_DIR="bin"

DOTNET_PATH=`which dotnet`
DOTNET_VERSION=`${DOTNET_PATH} --version`
DOTNET_VERSION_MAJOR_AND_MINOR=${DOTNET_VERSION:0:3}
DOTNET_TARGET_FRAMEWORK="net${DOTNET_VERSION_MAJOR_AND_MINOR}"

echo "Making directory for ${OUTPUT_PRODUCT_NAME} build"
mkdir -p "${BUILD_DIR}"

OUTPUT_FILE_PATH_X64=".${OUTPUT_PRODUCT_NAME}_x64"
OUTPUT_FILE_PATH_ARM64=".${OUTPUT_PRODUCT_NAME}_ARM64"
OUTPUT_FILE_PATH_UNIVERSAL="${OUTPUT_PRODUCT_NAME}"

C_HEADER_FILE_NAME="Generated_C.h"

./build_dependencies_macos_universal

cd "${BUILD_DIR}"

echo "Copying native library"
cp "../../Beyond.NET.Sample.Native/bin/Release/${DOTNET_TARGET_FRAMEWORK}/osx-universal/publish/${LIBRARY_FILE_NAME}" "${LIBRARY_FILE_NAME}"

echo "Copying C header file"
cp "../../Generated/${C_HEADER_FILE_NAME}" "${C_HEADER_FILE_NAME}"

echo "Copying C file"
cp "../${C_FILE_NAME}" "${C_FILE_NAME}"

echo "Building ${OUTPUT_PRODUCT_NAME} for x64"
clang -Wl,-rpath,. -L. -l${LIBRARY_NAME} -arch "x86_64" -o "${OUTPUT_FILE_PATH_X64}" "${C_FILE_NAME}"

echo "Building ${OUTPUT_PRODUCT_NAME} for ARM64"
clang -Wl,-rpath,. -L. -l${LIBRARY_NAME} -arch "arm64" -o "${OUTPUT_FILE_PATH_ARM64}" "${C_FILE_NAME}"

echo "Making universal ${OUTPUT_PRODUCT_NAME} build"
lipo -create "${OUTPUT_FILE_PATH_X64}" "${OUTPUT_FILE_PATH_ARM64}" -output "${OUTPUT_FILE_PATH_UNIVERSAL}"

echo "Deleting ${OUTPUT_PRODUCT_NAME} x64 build"
rm "${OUTPUT_FILE_PATH_X64}"

echo "Deleting ${OUTPUT_PRODUCT_NAME} ARM64 build"
rm "${OUTPUT_FILE_PATH_ARM64}"

echo "Deleting ${C_HEADER_FILE_NAME}"
rm "${C_HEADER_FILE_NAME}"

echo "Deleting ${C_FILE_NAME}"
rm "${C_FILE_NAME}"