#!/usr/bin/env bash

# See https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/docs/android-bionic.md for instructions

set -e

# Replace the next two values to match your Android NDK installation 
ANDROID_NDK_PATH="/Applications/AndroidNDK11579264.app/Contents/NDK"
ANDROID_OS_ARCH="darwin-x86_64"

ANDROID_NDK_BIN_PATH="${ANDROID_NDK_PATH}/toolchains/llvm/prebuilt/${ANDROID_OS_ARCH}/bin"

echo "Android NDK Bin Path: ${ANDROID_NDK_BIN_PATH}"

export PATH=${ANDROID_NDK_BIN_PATH}:$PATH

OUTPUT_PRODUCT_NAME="libBeyondDotNETSampleNative"
BUILD_CONFIGURATION="Release"

OUTPUT_FILE_NAME="${OUTPUT_PRODUCT_NAME}.so"

DOTNET_PATH=`which dotnet`
DOTNET_VERSION=`${DOTNET_PATH} --version`
DOTNET_VERSION_MAJOR_AND_MINOR=${DOTNET_VERSION:0:3}

VERBOSITY_LEVEL="normal"

RUNTIME_IDENTIFIER_ARM64="linux-bionic-arm64"

BIN_DIR="bin"
PUBLISH_DIR="publish"
DOTNET_TARGET_FRAMEWORK="net${DOTNET_VERSION_MAJOR_AND_MINOR}"

ARM64_BUILD_DIR="${BIN_DIR}/${BUILD_CONFIGURATION}/${DOTNET_TARGET_FRAMEWORK}/${RUNTIME_IDENTIFIER_ARM64}/${PUBLISH_DIR}"

ARM64_FILE_PATH="${ARM64_BUILD_DIR}/${OUTPUT_FILE_NAME}"

echo "Cleaning ${OUTPUT_PRODUCT_NAME}"
${DOTNET_PATH} clean /p:Configuration=Release

echo "Building ${OUTPUT_PRODUCT_NAME} for Android ARM64"
${DOTNET_PATH} publish \
  -r ${RUNTIME_IDENTIFIER_ARM64} \
  -v "${VERBOSITY_LEVEL}" \
  -p:PublishAotUsingRuntimePack=true